### ISSUE TITLE
Option to not overwrite existing data

### ISSUE THREAD

**Issue by shellscape** [luisrudge/prisma-generator-fake-data#10]
Great generator, thanks for putting this together. Was wondering if it would be possible to add a flag that would instruct the generator not to overwrite existing fakes. We'd like to keep this in our schema and generate from our schema often, but also use snapshots in our tests, so we need to assert the same data exists between `generate` operations.

Progressive generation would also be cool, where the fake data generator would only generate data for types/methods that don't already exists, but that's probably a big ask.

**Comment by shellscape** [comment]
Not quite what I was getting at. To start, simply checking if the output file exists and skipping the generation, if the flag was present.

**Comment by luisrudge** [comment]
wouldn't that prevent the generator to run for the second time, though?

- set flag to true
- `npx prisma generate` generates the file for the first time
- add a property to a model
- `npx prisma generate` wouldn't update the generated method for the model because of the flag

**Comment by shellscape** [comment]
Correct. With the use of `env(...)` in the prisma file, that can be an externally controlled flag.

**Comment by luisrudge** [comment]
What's the use case for preventing it to run?

**Comment by shellscape** [comment]
> We'd like to keep this in our schema and generate from our schema often, but also use snapshots in our tests, so we need to assert the same data exists between generate operations.

- Snapshot use is a core tenet of our testing paradigm
- We run generators as part of our build processes and CI
- When using fake data for snapshots in testing, you _don't_ want the fakes (aka fixtures) to change on each run.
- Seeding defeats the purpose of using a tool like this because we'd have to seed everything manually. 
- Changing fake data (aka fixtures) on each generate call would cause tests using snapshots to fail. Consider onboarding new users, fresh clones of the repo, running in CI

**Comment by luisrudge** [comment]
gotcha. I think I get it now.

Currently, we generate methods like this:

```ts
export function fakeUser() {
  return {
    email: faker.internet.email(),
    name: faker.name.fullName(),
    age: faker.datatype.number({ min: 0, max: 99 }),
  };
}
```

To be compatible with snapshot testing, your suggestion is that we change the output (maybe with a flag) to:

```ts
export function fakeUser() {
  return {
    email: 'Ella.Mayer@gmail.com', //generated by calling faker.internet.email()
    name: 'Lana Gulgowski', //generated by calling faker.name.fullName()
    age: 81, //generated by calling faker.datatype.number({ min: 0, max: 99 })
  };
}
```

On top of that, add a flag to prevent the generator to override the file.

Did I get this right?

**Comment by shellscape** [comment]
I legit didn't look at the source nor the generated source before opening the issue (and I should have, that's on me. you have my apologies). I didn't realize that you were basically piping `faker`. So yes, that's what I was hoping for in the generated output, which would make sense in the context of my request.

But I also realize that's a huge (maybe unreasonable) ask and quite a paradigm shift. If you're up for that, awesome. If not, I totally understand.

**Comment by luisrudge** [comment]
I actually think it makes sense to have a flag to do this if it means we can support snapshot testing. I just can't picture the dev workflow in my head to justify the work. 

- dev1: `npx prisma generate`  for the first time and generates the file (with the changes we mentioned)
- dev2: adds a new field
- dev2: runs `npx prisma generate` and nothing happens because they have the flag set to true
- dev2: sets the flag to false, runs `npx prisma generate` again and then all the tests will fail because the fake values changed

So I think we can only implement this if we use the progressive generation approach you mentioned in your first comment: only add new properties, but don't update the current ones.

Actually, if we had a way to progressively generate only the new types, we can even get away without the flag, since the generator would not touch the current properties anyway. 🤔 

I wish there was an easier way to support snapshots, honestly.  But it feels like you'd be better of manually generating the methods.

**Comment by shellscape** [comment]
Yeah the workflow would't be smooth for new columns, tables. One would have to diff and pull in the new stuff to the old fixtures.

> But it feels like you'd be better of manually generating the methods.

Given the amount of data we'd need to manually generate that's equally not ideal (which is what led me here).

I think a fork might be a good path to introduce a static export, which would make progressive changes much easier. We could pick this back up when I have the chance to make that.

**Comment by luisrudge** [comment]
> Given the amount of data we'd need to manually generate that's equally not ideal (which is what led me here).

Yeah, that makes sense. Maybe you could generate once with this tool, then remove the generator and only do the adjustments manually.

Anyway, thanks for the discussion! If you want to open a PR with a flag for static exports, I'd be more than happy to merge it in (assuming it fixes your problem with a nice workflow).
