### ISSUE TITLE
Option to default to null instead of undefined?

### ISSUE THREAD

**Issue by tysoncadenhead** [luisrudge/prisma-generator-fake-data#11]
I just stumbled upon this repo and it's awesome! I was wondering if we could get an option to default  empty output to `null` instead of `undefined` as it is currently not the correct type for my outputs. Thanks!

**Comment by luisrudge** [comment]
@tysoncadenhead thanks for opening the issue! My initial approach was setting the value to null, but Prisma didn't like that much considering they treat null and undefined in different ways (https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined). I'm just wondering if generating empty values as null would case any issues down the road.

**Comment by luisrudge** [comment]
release in https://github.com/luisrudge/prisma-generator-fake-data/releases/tag/v0.9.0 under option `emptyValueAs`

**Comment by tysoncadenhead** [comment]
Thanks, this is exactly what I needed! For my use-case, I was wanting to generate the same type I got back from a `findFirst`, which typescript wanted to be all nulls, so this helped with that

**Comment by luisrudge** [comment]
@tysoncadenhead awesome! glad to know it's working
