### ISSUE TITLE
Invalid import paths for generated imports on Windows

### ISSUE THREAD

**Issue by ChristianRaoulis** [luisrudge/prisma-generator-fake-data#23]
the generated fake-data.ts file starts with an invalid import for me.

It looks like this:
```ts
import { MyTestModel } from 'C:\Users\A92615470\IdeaProjects\frontend-privat\node_modules\.pnpm\@prisma+client@5.10.2_prisma@5.10.2\node_modules\@prisma\client';
```

but should look like this:

```ts
import { MyTestModel } from '@prisma/client';
```

Any Idea what could be the reason for that?

I'm on windows and use pnpm btw.

**Comment by luisrudge** [comment]
yeah, I know what's going on: https://github.com/luisrudge/prisma-generator-fake-data/commit/0ff142467ea4a96195ed4b9528c531a4c3c70d92#diff-88bbc52eace2b1a54d791becb61ae7e5d76c6669d37644774977acdebe044f02R14

I fixed this but didn't account for windows path (inverted slash). I'll fix it today. Thanks for the report!

**Comment by luisrudge** [comment]
fixed in https://github.com/luisrudge/prisma-generator-fake-data/commit/56ec5e0678c776dccf12dcb2ecb4c9aa3a83671e
