### ISSUE TITLE
Support Prettier or a post-generate script

### ISSUE THREAD

**Issue by FezVrasta** [luisrudge/prisma-generator-fake-data#24]
Would it be possible to have an option to run Prettier on the generated file, or at least run an arbitrary script, so that I can run Prettier on it?

Right now the file keeps changing format back and forth and it's not a great experience.

**Comment by luisrudge** [comment]
I think this is something you should do after you `prisma generate` if you really need it.

In my project, the file is git ignored, so I don't see the point of doing any formatting. As with most generated files, I don't care how it looks, as long as it has all that I need inside of it.
